cmd/auth.go, cmd/deploy.go, cmd/provisionaccounts.go, cmd/root.go, lib/awsorgs/organization.go
1) Add diff command. The `deploy` command relied on `--require-approval` to show output for a deploy without applying the changes. This flag is for security changes https://docs.aws.amazon.com/cdk/v2/guide/cli.html. I introduced the `diff` command to follow CDK pattern
2) Make backend calls to Telophase if the user has a telophase api key in their env
=> Add diff command + telophase calls

cmd/deploy.go, cmd/diff.go, cmd/iac.go, lib/ymlparser/organization.go
This feature allows you to specify stacks for each account in organization.yml.
Benefits:
1. Apply multiple TF or CDK stacks to each account in a single cli run.
2. Stack <-> Account association in version control.
=> Associate accounts with Stacks to apply

cmd/deploy.go, cmd/diff.go, cmd/provisionaccounts.go, lib/awsorgs/organization.go, lib/ymlparser/aws_ops.go, lib/ymlparser/organizationv2.go
CDK/TF used `diff` and `deploy` commands. Account provisoning uses `plan` and `apply` commands. This is confusing. We're focusing on CDK support for now, so let's standardize on CDK commands
=> use diff/deploy for account provisioning

cmd/deploy.go, cmd/diff.go, cmd/iac.go, cmd/runner/interface.go, cmd/runner/stdout.go, cmd/runner/tui.go
This is the first step of a larger refactor to merge the logic for org, SCP, and iac changes
This PR does two things
1. moves the logic for making org changes to the command (eg `diff.go`) logic.
2. Merges the tui and stdout into a single deploy path
=> Merge TUI and STD out

cmd/deploy.go, cmd/diff.go, cmd/provisionaccounts.go, cmd/root.go, resourceoperation/account.go, resourceoperation/organization_unit.go
The change that moved the bulk of the logic for `diff`, `deploy`, and `account` into its own function  broke printing to stdout. That function should only be run in a gothread for `tui`
=> run process in main thread for stdout.

cmd/root.go, resourceoperation/organization_unit.go
IAC operations were running on `account diff/deploy`. That should not happen
=> dont add iac operations as dependents of account creation

cmd/provisionaccounts.go, cmd/root.go, lib/awsorgs/organization.go, lib/ymlparser/organizationv2.go, resource/account.go, resource/organization_unit.go, resourceoperation/scp.go, tests/end2end_test.go
This change add support for deploying SCP changes from a [delegated administrator](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_delegate_policies.html). I fixed two bugs along the way
1. `FetchOUAndDescendents` was not setting the `ManagementAccount` flag becuase pointer addresses were compared instead of the values (lol)
2. `ManagementAccount` flag was not set during yml parsing
=> Delegated Admin

examples/cdk/tf-s3-backend/app.go, examples/cdk/tf-s3-backend/go.mod, resourceoperation/cdk.go
`telophaseAccountId` is now available in cdk context to reference your Account ID. 
You can fetch it in your cdk code with `accountId := stack.Node().TryGetContext(jsii.String("telophaseAccountId")).(string)`
=> pass account id into cdk context

cmd/deploy.go, cmd/diff.go, cmd/root.go, resourceoperation/scp.go, setup.sh, tests/end2end_test.go, tests/main_test.go, tests/tf/s3-test/main.tf, tests/tf/scp-test/main.tf
Before this pr, all resources (ie Organization, SCP, and Stacks) were all included with `telophasecli deploy` and `telophasecli diff`. This change introduces a `--targets` flag that allows you to filter the resource:
`telophasecli --targets=scp` to deploy SCPs
`telophasecli --targets=organization` to deploy Organization
`telophasecli --target=stacks` to deploy Stacks
You can specify multiple targets:
`telophasecli --targets=organization,scp` to deploy SCPs and Organization
etc
=> Split SCP, Organization, and Stacks Commands

tests/end2end_test.go
Tests are really slow. We were creating resources that did not contribute to test coverage but slowed down the test.
=> tests: remove unnecessary and expensive awslocal calls

cmd/deploy.go, cmd/diff.go, cmd/root.go, lib/awsorgs/organization.go
`strings.Split("", ",")` returns an array with a single item, `""`. This caused the logic gated by `if len(targets) == 0` to be skipped
=> Handle Empty Targets 

examples/localstack/organization.yml, examples/localstack/setup.sh, examples/localstack/tf/workspace/main.tf, lib/awssts/awssts.go, lib/terraform/local.go, mintlifydocs/config/organization.mdx, mintlifydocs/features/Assign-IaC-Blueprints-To-Accounts.mdx, resource/stack.go, resourceoperation/cdk.go, resourceoperation/scp.go, resourceoperation/terraform.go
This allows a user to specify the Terraform workspace and it can be
interpolated with ${telophase.account_id} or ${telophase.region} into
the workspace name.
=> resource: allow user to specify a terraform workspace

cmd/iac.go, mintlifydocs/config/organization.mdx, mintlifydocs/features/Assign-IaC-Blueprints-To-Accounts.mdx, resource/account.go, resource/stack.go, resourceoperation/account.go
The region can now be set to:
-  `"all"` will deploy to all enabled regions within the specific account. 
- comma-separated list of regions to deploy to. For example: `"us-west-2,eu-west-1"`
Also bubble up some errors to the top level in this PR
=> Allow region to be "all" or a comma separated list

lib/awsorgs/organization.go, lib/terraform/local.go, lib/ymlparser/organizationv2.go, resource/account.go
- Before when you targeted with `--stack=` and a terraform workspace was set then we would remove the Workspace setting. This now preserves the stacks settings through
- Preserve file mode when copying over. This would allow someone to set the provider in the `Stack` path and then reuse it when copied over to `telophasedirs`
- Add an error message if using a role that doesn't have access to the organizations API. This was failing before with an AccessDenied and not obvious to an end user
=> Allow Stack targeting with workspaces

mintlifydocs/config/organization.mdx, mintlifydocs/features/Assign-IaC-Blueprints-To-Accounts.mdx, resource/stack.go, resource/stack_test.go, resourceoperation/cdk.go, resourceoperation/terraform.go
Use AssumeRoleName instead of AssumeRoleARN because we will be able to generate
the ARN based on what account the stack is applied to.
=> AssumeRoleName on stacks

mintlifydocs/config/organization.mdx, mintlifydocs/features/Assign-IaC-Blueprints-To-Accounts.mdx, resourceoperation/cdk.go
The `Name` within `Stacks` go struct has caused confusion so we default to deploying all CDK stacks so that the Name can be used alongside terraform stacks and filter.
The original intention of `Name` was to be able to target CDK stacks, but we want to provide filtering on terraform and cdk stacks. We can always add back CDK stack filtering by allowing an end user to pass in additional flags to the CDK or specifying CDKStacks. For now, we are removing the feature
=> resourceop: deploy all CDK stacks by default

cmd/provisionaccounts.go, cmd/root.go, lib/ymlparser/organization.go, tests/end2end_test.go
We no longer parse the orgv1 so lets remove all v2 references
=> ymlparser: remove orgv2 suffix

resourceoperation/cdk.go
Now stack.RoleARN will use the account's role if the stack's is not set
=> resourceop cdk: bootstrap with stack role

cmd/root.go, lib/awsorgs/organization.go, lib/ymlparser/organization.go, mintlifydocs/commands/deploy.mdx, mintlifydocs/config/organization.mdx, resource/account.go, resource/organization_unit.go, resourceoperation/account.go, resourceoperation/interface.go, resourceoperation/organization_unit.go
This PR supports tagging at the OU and Account level. You can now:
- Tag resources in telophase and result in tagging within AWS via an `=` delimited string. - For example, `env=prod` will create a tag with key `env` and value `prod` - If there is no `=` then the value will be empty on the AWS tag.
- Account tags will inherit tags from their OU parent tree
=> *: support OU and account AWS Tags

examples/cloudformation/dynamo/table.yml, resource/account.go, resource/stack.go, resourceoperation/account.go, resourceoperation/cloudformation.go
This allows you to define a cloudformation stack like:
```
- Type: "Cloudformation"
Path: "examples/cloudformation/dynamo/table.yml"
Name: "painter3"
CloudformationParameters:
- "HashKeyElementName=Painter"
```
We use the Name and path to ensure that stacks are unique.
Cloudformation support depends on change sets that we use to update a
deployed stack as the cloudformation changes.
The Path for cloudformation should go directly to the template you want
to use. Unlike terraform and CDK where there is a directory of contents.
=> resource: support cloudformation stack type

cmd/deploy.go, cmd/diff.go, cmd/iac.go, cmd/root.go, go.mod, go.sum
If the diff or deploy fail then we want to ensure that telophase exits with a non-zero status code.
This makes it easier to use in a script with set -e to show up as red when telophasecli is used in CI
=> cmd: exit 1 if cdk, cloudformation or terraform fail

examples/cloudformation/iam/role.yml, mintlifydocs/config/organization.mdx, mintlifydocs/features/Assign-IaC-Blueprints-To-Accounts.mdx, resource/stack.go, resource/stack_test.go, resourceoperation/cloudformation.go
Cloudformation requires setting these capabilities if you are making
certain changes. For example, IAM changes require setting a capability
https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html#API_CreateStack_RequestParameters
=> Support CloudformationCapabilities for Stacks

lib/awssts/awssts.go, resourceoperation/cdk.go, resourceoperation/cloudformation.go, resourceoperation/scp.go, resourceoperation/terraform.go
In the management account if we try to assume the
OrganizationAccountAccessRole and fail we should use the default
credentials and assume they are in the management account.
The OrganizationAccountAccessRole is created by default in child
accounts, but not in the management account.
=> resource: use current user if in management account

lib/awsorgs/organization.go, resourceoperation/cdk.go
Sometimes people want to assume roles via terraform or CDK and defer to
their local credentials. In this case, let them override it with an
environment variable.
=> resourceop cdk: skip assume role if TELOHASE_BYPASS_ASSUME_ROLE is se

cmd/provisionaccounts.go, cmd/root.go, lib/awsorgs/awsorgsmock/organizationmock.go, lib/awsorgs/organization.go, lib/ymlparser/organization.go, lib/ymlparser/organization_test.go, lib/ymlparser/testdata/organization-basic.yml, lib/ymlparser/testdata/organization-child.yml, lib/ymlparser/testdata/organization-child2.yml, lib/ymlparser/testdata/organization-with-filepath.yml, mintlifydocs/config/organization.mdx, resource/organization_unit.go, tests/end2end_test.go
Closes: https://github.com/Santiago-Labs/telophasecli/issues/75
This allows users to specify OUs within separate files. For example:
```yml
Organization:
Name: root
OrganizationUnits:
- OUFilepath: "./testdata/organization-child.yml"
- OUFilepath: "./testdata/organization-child2.yml"
```
This can be helpful to clean up the main `organization.yml` and also allows for CODEOWNERS to own their own OUs and account applying
=> Support OUFilepath within an OrganizationUnit

cmd/deploy.go, cmd/provisionaccounts.go, cmd/root.go, lib/awsorgs/organization.go, lib/ymlparser/organization.go, mintlifydocs/config/organization.mdx, resource/account.go, resourceoperation/account.go, resourceoperation/interface.go, resourceoperation/organization_unit.go, tests/end2end_test.go, tests/main_test.go
This will close the account and by default have 90 days to recover it. Closes https://github.com/Santiago-Labs/telophasecli/issues/79
=> resourceop account: add Delete to an account for closing it

lib/awsorgs/organization.go, mintlifydocs/config/organization.mdx, resource/account.go, resourceoperation/account.go, resourceoperation/interface.go, resourceoperation/organization_unit.go
This allows someone to delegate different service principals to accounts managed in telophase. One example is:
```
OrganizationUnits:
- Name: Security
Accounts:
- Email: example+audit@example.com
AccountName: Audit
DelegatedAdministratorServices:
- "config.amazonaws.com"
- "config-multiaccountsetup.amazonaws.com"
```
This will end up calling `register-delegated-admin` with the listed service principals on the account defined.
=> resourceop account: allow delegating services to accounts

resource/account.go, resource/account_test.go
You can now set NoStackInheritance: true for an account. This will make it so that a stack doesn't inherit from the current OU or parent OUs.
The most useful case for this is when you have the management account at the top level and want to declare top level stacks as well to target all sub accounts except the management account.
=> resource account: allow setting NoStackInheritance
